# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9d9f1a09d5ebce4496721750fdbb6a67563d8d13674658425a8fa0c8dcd87893ed871d7cb40082bff2ae44901fa5d94ea9dabb9e6f61c2c187aa1d5bc957a82

test:
  secret_key_base: b7a468737bef518f7e34ef60a80872d96d42aaa146b529bfc93f0bbc3d9e42bfdc3599dc002aba11453ca857f4ad4e0652b5a9eac7908d048a313a1b3743e561

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
